---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - data:/tmp/App44/target/
      - mysql:/tmp/App44/ 

  prod:      
    image: tomcat:9.0
    ports:
      - "8081:8080"
    links:
      - db    
    volumes:
      - data:/usr/local/tomcat/webapps/
      - mysql:/tmp/App44/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: acp4pogynvaeidfj
       MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw  
    depends_on:
      - app
      - db

  db:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: acp4pogynvaeidfj
       MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "8514:3306"    
    volumes:
      - mysql:/tmp/App44/

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root    
      
volumes:
  data:
  mysql:     
