---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - /data:/tmp/App44/target/ 

  prod:      
    image: tomcat:9.0
    ports:
      - "8081:8080"
    links:
      - bd    
    volumes:
      - /data:/usr/local/tomcat/webapps/
    depends_on:
      - app
      - bd

  bd:
    image: mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=secret
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
    ports:
      # - "3306:8514"
      - "3306:3306"    
    volumes:
      - ./mysql:/var/lib/mysql
