---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - data:/tmp/App44/target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT

  prod:      
    image: tomcat:9.0
    # build: prod
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db   
    environment:
      MYSQL_HOST: db
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DB: db  
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/usr/local/tomcat/webapps/
    

  db:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: acp4pogynvaeidfj
       MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "8514:3306"    
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root     
      
volumes:
  data: 