---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - data:/tmp/App44/target/

  prod:      
    image: tomcat:9.0
    depends_on:
      - app
      - db
    ports:
      - "8081:8080"
    links:
      - db   
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: acp4pogynvaeidfj
       MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    # environment:
    #   DB_HOST: db
    #   DB_USER: acp4pogynvaeidfj
    #   DB_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    #   DB_NAME: db 
    volumes:
      - data:/usr/local/tomcat/webapps/
    

  db:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: acp4pogynvaeidfj
       MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "3306:3306"    
    volumes:
      - ./mysql:/var/lib/mysql
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root     
      
volumes:
  data:    
